version: '3'
services:
  mongo:
    restart: always
    image: mongo
    env_file:
      - .env
  server:
    build: "./"
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    
  